# This is a basic workflow that is manually triggered

name: Rebase dev after merge from main


on:
  workflow_dispatch:

jobs:
  rebaseDev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
     - uses: actions/checkout@v3
     - name: Rebase dev after merge
       run: |
        git fetch origin
        git pull
        git rebase origin/main
        git push -f
